#!/bin/bash
#SBATCH --job-name=vec2vec
#SBATCH --output=logs/%A.out
#SBATCH --time=1-00:00:00
#SBATCH --gres=gpu:a100_40gb:1
#SBATCH --partition=acltr

clap_model="clap"
model="gte"

apptainer exec --nv -B /home/edlu/vec2vec/:/v2v vec_image.sif bash -c "
    export HOME=/v2v/.cache/job_${SLURM_JOB_ID}_$(printf "%x" $SLURM_ARRAY_TASK_ID)
    micromamba run -n vec wandb login $WANDB_TOKEN
    micromamba run -n vec python -s /v2v/train.py unsupervised \
        --epochs 100 \
        --num_points 1000000 \
        --sup_emb $clap_model \
        --unsup_emb $model
"