#!/bin/bash
#SBATCH --job-name=vec2vec
#SBATCH --array=0-1%1
#SBATCH --gres=gpu        
#SBATCH --partition=scavenge

nvidia-smi 

models=(
    "granite"
    "gtr"
    "gte"
    "stella"
    "e5"
    "clip"
)

clap_model="clap"

unsup_idx=$SLURM_ARRAY_TASK_ID
model=${models[$unsup_idx]}
sup=$clap_model

apptainer exec --nv -B /home/edlu/vec2vec/:/v2v vec.sif bash -c "
    export WANDB_DISABLE_SSL_VERIFY=true
    export WANDB_TOKEN=$WANDB_TOKEN
    micromamba run -n vec wandb login $WANDB_TOKEN
    micromamba run -n vec python -s /v2v/train.py unsupervised \
        --epochs 69 \
        --num_points 1000000 \
        --sup_emb $model\
        --unsup_emb $clap_model
"