#!/bin/bash
#SBATCH --job-name=vec2vec
#SBATCH --output=logs/%A.out
#SBATCH --time=1-00:00:00
#SBATCH --gres=gpu
#SBATCH --partition=scavenge

nvidia-smi

apptainer exec --nv -B /home/edlu/vec2vec/:/v2v vec_image.sif bash -c "
    export HOME=/v2v/.cache/job_${SLURM_JOB_ID}_$(printf "%x" $SLURM_ARRAY_TASK_ID)
    micromamba run -n vec python -s /v2v/universal.py finetuning_unsupervised/e:100,n:1000000,s:clap,u:e5
"